import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

type CommandSegment = {
  kind: 'literal' | 'required' | 'argument';
  name: string;
  token: string;
  description?: string;
  argumentType?: string;
  valueType?: string;
};

type CommandFlag = {
  name: string;
  token: string;
  description?: string;
  argumentType?: string;
  valueType?: string;
  presenceOnly: boolean;
};

type CommandEntry = {
  root: string;
  rootAliases?: string[];
  syntax: string;
  description?: string;
  permission?: string;
  senderType?: string;
  segments: CommandSegment[];
  flags: CommandFlag[];
};

type CommandSchema = {
  pluginVersion: string;
  commands: CommandEntry[];
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const docsRoot = path.resolve(__dirname, '..');
const defaultSource = path.resolve(
  docsRoot,
  '..',
  'notquests',
  'src',
  'paper',
  'run',
  'plugins',
  'NotQuests',
  'generated',
  'commands.json',
);
const source = process.argv[2] ? path.resolve(process.argv[2]) : defaultSource;
const output = path.join(docsRoot, 'docs', 'documentation', 'command-reference.mdx');
const schemaOutput = path.join(docsRoot, 'src', 'remarkplugins', 'command-schema.generated.json');

if (!fs.existsSync(source)) {
  console.error(`Command schema not found: ${source}`);
  console.error('Run the plugin E2E sweep first, or pass a schema path: pnpm update-commands -- <path>');
  process.exit(1);
}

const schema = JSON.parse(fs.readFileSync(source, 'utf8')) as CommandSchema;
const commands = [...schema.commands].sort((a, b) => displaySyntax(a).localeCompare(displaySyntax(b)));
const grouped = new Map<string, CommandEntry[]>();

validateDescriptions(commands);

const compactSchema: CommandSchema = {
  pluginVersion: schema.pluginVersion,
  commands: commands.map((command) => ({
    root: command.root,
    rootAliases: command.rootAliases || [],
    syntax: command.syntax,
    description: command.description || '',
    permission: command.permission || '',
    senderType: command.senderType || 'any',
    segments: command.segments.map((segment) => ({
      kind: segment.kind,
      name: segment.name,
      token: segment.token,
      description: segment.description || '',
      argumentType: segment.argumentType || '',
      valueType: segment.valueType || '',
    })),
    flags: command.flags.map((flag) => ({
      name: flag.name,
      token: flag.token,
      description: flag.description || '',
      argumentType: flag.argumentType || '',
      valueType: flag.valueType || '',
      presenceOnly: flag.presenceOnly,
    })),
  })),
};

fs.writeFileSync(schemaOutput, `${JSON.stringify(compactSchema)}\n`, 'utf8');

for (const command of commands) {
  const group = groupName(command);
  if (!grouped.has(group)) {
    grouped.set(group, []);
  }
  grouped.get(group)?.push(command);
}

let mdx = `---
title: Command Reference
sidebar_position: 3
description: Generated NotQuests command reference built from the plugin's native command tree
keywords: [notquests, command reference, commands, qa, q, generated commands]
---

{/*
  This file is generated by scripts/update-command-reference.mts from the plugin's exported
  commands.json. Do not edit command entries by hand.
*/}

# Command Reference

This page is generated from NotQuests ${escapeText(schema.pluginVersion)}'s native command tree.
It contains ${commands.length.toLocaleString('en-US')} executable command shapes.

Hover an argument or flag to see the description exported by the plugin. Required arguments use
\`<argument>\`; optional flags use \`[--flag]\` or \`[--flag <value>]\`.

:::tip
In game, tab-completion is still the best way to discover context-sensitive values like quest names,
tags, categories, players, worlds, materials, and custom items.
:::

:::info Platform capabilities
This reference reflects the platform capabilities present when the schema was exported. Shared
commands are the same on Paper and NeoForge. Integration-only or platform-capability commands are
registered only where that feature is available.
:::

`;

for (const [group, entries] of grouped) {
  mdx += `\n## ${escapeText(group)}\n\n`;
  mdx += `<div className="commandReferenceList">\n`;
  for (const command of entries) {
    mdx += commandCard(command);
  }
  mdx += `</div>\n`;
}

fs.writeFileSync(output, mdx, 'utf8');
console.log(`Wrote ${commands.length} commands to ${path.relative(docsRoot, output)}`);
console.log(`Wrote build-time schema to ${path.relative(docsRoot, schemaOutput)}`);

function commandCard(command: CommandEntry): string {
  const description = command.description || '';
  const meta = [
    command.permission ? `Permission: ${command.permission}` : '',
    command.senderType && command.senderType !== 'any' ? `Sender: ${command.senderType}` : '',
  ].filter(Boolean);

  return `<div className="commandReferenceCard">
  <div className="commandReferenceSyntax">${renderSyntax(command)}</div>
  ${description ? `<div className="commandReferenceDescription">${escapeHtml(description)}</div>` : ''}
  ${meta.length ? `<div className="commandReferenceMeta">${escapeHtml(meta.join(' · '))}</div>` : ''}
</div>
`;
}

function renderSyntax(command: CommandEntry): string {
  let argumentHighlightIndex = 0;
  const segments = command.segments.map((segment, index) => {
    const token = index === 0 ? displayRoot(segment.name) : segment.token;
    const css = segment.kind === 'literal'
      ? 'commandRichToken commandRichToken--literal'
      : `commandRichToken commandRichToken--argument commandRichToken--${minecraftHighlightSemantic(argumentHighlightIndex++)}`;
    const title = segmentTitle(segment, index === 0 ? token : segment.token);
    const prefix = index === 0 ? '/' : '';
    return `${index === 0 ? '' : ' '}${richToken(css, `${prefix}${token}`, title)}`;
  }).join('');

  const flags = command.flags.map((flag) => {
    const token = `[${flag.token}]`;
    return ` ${richToken('commandRichToken commandRichToken--flag', token, flagTitle(flag))}`;
  }).join('');

  return segments + flags;
}

function minecraftHighlightSemantic(index: number): string {
  return ['minecraftAqua', 'minecraftYellow', 'minecraftGreen', 'minecraftLightPurple', 'minecraftGold'][index % 5];
}

function segmentTitle(segment: CommandSegment, token: string): string {
  const lines = [];
  lines.push(token);
  if (segment.description) {
    lines.push(segment.description);
  }
  const accepts = segment.kind === 'literal' ? '' : segment.valueType || '';
  if (accepts) {
    lines.push(`Accepts: ${accepts}`);
  }
  return lines.join('\n');
}

function richToken(className: string, value: string, title: string): string {
  return `<span className="${className}" aria-label="${escapeAttribute(title)}">${escapeHtml(value)}${tooltipHtml(title)}</span>`;
}

function tooltipHtml(title: string): string {
  const [heading, ...lines] = title.split('\n').filter(Boolean);
  const body = lines.map(tooltipRowHtml).join('');
  return `<span className="commandRichTooltip" aria-hidden="true"><span className="commandRichTooltipTitle">${escapeHtml(heading || 'Command detail')}</span>${body}</span>`;
}

function tooltipRowHtml(line: string): string {
  const match = line.match(/^(Accepts|Example|Full command):\s*(.*)$/);
  if (!match) {
    return `<span className="commandRichTooltipDescription">${escapeHtml(line)}</span>`;
  }
  return `<span className="commandRichTooltipRow"><span className="commandRichTooltipLabel">${escapeHtml(match[1])}</span><span className="commandRichTooltipValue">${escapeHtml(match[2])}</span></span>`;
}

function validateDescriptions(commands: CommandEntry[]): void {
  const errors: string[] = [];
  for (const command of commands) {
    for (const segment of command.segments) {
      if (weakDescription(segment.description, segment.name, segment.token)) {
        errors.push(`${command.syntax}: ${segment.token} -> ${JSON.stringify(segment.description || '')}`);
      }
    }
    for (const flag of command.flags) {
      if (weakDescription(flag.description, flag.name, flag.token)) {
        errors.push(`${command.syntax}: --${flag.name} -> ${JSON.stringify(flag.description || '')}`);
      }
    }
  }
  if (errors.length) {
    throw new Error(
      `Command schema has ${errors.length} weak description(s). Fix the plugin command registrations first:\n`
      + errors.slice(0, 80).map((error) => `  - ${error}`).join('\n')
      + (errors.length > 80 ? `\n  ... ${errors.length - 80} more` : ''),
    );
  }
}

function weakDescription(description: string | undefined, name: string, token: string): boolean {
  const text = String(description || '').trim();
  if (!text || text === 'Variable Name') {
    return true;
  }
  const weakPhrases = new Set([
    'adds a new entry in this command branch.',
    'checks the selected value or condition.',
    'creates a new entry.',
    'deletes the selected entry.',
    'lists matching entries.',
    'opens edit commands for the selected entry.',
    'optional command flags for this command.',
    'removes all entries in this command branch.',
    'removes the selected entry or value.',
    'sets a new value.',
    'shows detailed information about the selected entry.',
    'shows or changes the category assigned to this entry.',
    'shows the current value.',
    'shows, sets, or removes user-facing description text.',
  ]);
  if (weakPhrases.has(text.toLowerCase())) {
    return true;
  }
  const candidates = [name, token.replace(/[\[\]<>]/g, '')]
    .map((value) => normalizeDescription(String(value || '')))
    .filter(Boolean);
  return candidates.includes(normalizeDescription(text));
}

function normalizeDescription(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
}

function flagTitle(flag: CommandFlag): string {
  const lines = [`--${flag.name}`];
  if (flag.description) {
    lines.push(flag.description);
  }
  if (!flag.presenceOnly) {
    const accepts = flag.valueType || '';
    if (accepts) {
      lines.push(`Accepts: ${accepts}`);
    }
  }
  return lines.join('\n');
}

function groupName(command: CommandEntry): string {
  const root = displayRoot(command.root);
  const second = command.segments[1]?.name;
  if (!second) {
    return root === 'qa' ? '/qa root' : '/q root';
  }
  return `/${root} ${second}`;
}

function displaySyntax(command: CommandEntry): string {
  return command.syntax.replace(/^\/nqa\b/, '/qa').replace(/^\/nq\b/, '/q');
}

function displayRoot(root: string): string {
  if (root === 'nqa') {
    return 'qa';
  }
  if (root === 'nq') {
    return 'q';
  }
  return root;
}

function escapeHtml(value: string): string {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('`', '&#96;');
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replaceAll('"', '&quot;').replaceAll('\n', '&#10;');
}

function escapeText(value: string): string {
  return String(value).replaceAll('{', '&#123;').replaceAll('}', '&#125;');
}
